version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/configs/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Tokyo
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      LANG: C.UTF-8
  rails:
    build:
      context: ./rails
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      TZ: Asia/Tokyo
      DB_HOST: mysql
      DB_USERNAME: $MYSQL_USER
      DB_PASSWORD: $MYSQL_PASSWORD
      LANG: C.UTF-8
    volumes:
      - ./rails/project:/project
    ports:
      - 3000:3000
    depends_on:
      - mysql
